# Generated by Django 4.1.5 on 2023-02-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Example',
            new_name='Administracion',
        ),
        migrations.RenameModel(
            old_name='Example',
            new_name='Economia',
        ),
        migrations.RenameModel(
            old_name='Example',
            new_name='Finanzas',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
